version: 1
appendOnly: true
labels:
  - label: 'type: feature'
    title: '^feat(\(.+\))?:.*'
  - label: 'type: fix'
    title: '^fix(\(.+\))?:.*'
  - label: 'type: docs'
    title: '^docs(\(.+\))?:.*'
  - label: 'type: style'
    title: '^style(\(.+\))?:.*'
  - label: 'type: refactor'
    title: '^refactor(\(.+\))?:.*'
  - label: 'type: test'
    title: '^test(\(.+\))?:.*'
  - label: 'type: chore'
    title: '^chore(\(.+\))?:.*'
  - label: 'type: perf'
    title: '^perf(\(.+\))?:.*'
  - label: 'type: build'
    title: '^build(\(.+\))?:.*'
  - label: 'type: ci'
    title: '^ci(\(.+\))?:.*'
  - label: 'type: revert'
    title: '^revert(\(.+\))?:.*'
