/**
 * Tiered tool-output trust registry for the multi-layer injection detection
 * pipeline (FR-030, FR-031).
 *
 * Every statically-registered tool in this repository MUST have an explicit
 * entry in `TOOL_TRUST_REGISTRY`. A companion self-test in
 * `apps/api/src/agent/__tests__/tool-trust.test.ts` enforces this by booting
 * a `ToolRegistry` with every `ToolProvider` registered, collecting all tool
 * names, and asserting each one appears below.
 *
 * **Any new tool added after this feature ships defaults to
 * `external_untrusted`** (Category 3) if it is missing from this registry.
 * The self-test will fail until a deliberate entry is added with an inline
 * justification. This is by design — it forces a security decision for every
 * new tool before merge.
 *
 * Categories (full spec in `specs/.../spec.md` FR-030):
 * - `system_generated` — no attacker path; bypass detection
 * - `already_detected` — already filtered by an earlier pipeline pass; bypass detection
 * - `external_untrusted` — direct attacker path; MUST pass every input-side layer
 * - `mixed` — blend of system and attacker-reachable fields; untrusted by default,
 *   with optional opt-in trust at subcommand/path granularity
 *
 * MCP tools are not listed here because their names are dynamic and channel-scoped.
 * Per research R9, MCP tools default to `external_untrusted` via the fallback
 * logic in `approval-gateway.wrapTools()` and admins can mark specific MCP
 * tool names as trusted via a per-channel `trust_mcp_tool` override in the
 * `detection_overrides` table.
 */

export type ToolTrustCategory =
  | 'system_generated'
  | 'already_detected'
  | 'external_untrusted'
  | 'mixed';

/**
 * Per-subcommand opt-in trust pattern for Category 4 (mixed) tools.
 * The pattern is tested against the tool's invocation arguments; a match
 * promotes that specific invocation from `mixed` to `system_generated` for
 * detection purposes.
 */
export interface TrustedSubcommandPattern {
  pattern: RegExp;
  justification: string;
}

export interface ToolTrustEntry {
  toolName: string;
  category: ToolTrustCategory;
  justification: string;
  trustedSubcommandPatterns?: readonly TrustedSubcommandPattern[];
}

/**
 * The authoritative registry. Every entry MUST carry an inline justification
 * that a security reviewer can audit in a PR diff.
 */
export const TOOL_TRUST_REGISTRY: readonly ToolTrustEntry[] = [
  // ── confirm_plan (injected by ApprovalGateway) ─────────────────────────────
  {
    toolName: 'confirm_plan',
    category: 'system_generated',
    justification:
      'Return value is the approval result (approved/rejected/timeout) generated by the ApprovalGateway itself. No attacker-controllable fields in the response.',
  },

  // ── Memory tools (apps/api/src/memory/tools.ts) ────────────────────────────
  {
    toolName: 'memory_save',
    category: 'system_generated',
    justification:
      'Write tool. Return value is { success: true } or { error: true, message }. The memory content being saved is attacker-controllable but it is the input, not the output — inputs are detected at the turn boundary before the tool is invoked.',
  },
  {
    toolName: 'memory_search',
    category: 'already_detected',
    justification:
      'Returns recalled channel memories. Per FR-025, MemoryEngine.assembleContext() routes every recalled memory through the detection pipeline before surfacing it, so by the time memory_search returns, the content has already been filtered.',
  },
  {
    toolName: 'memory_list',
    category: 'already_detected',
    justification:
      'Returns the same recalled memories as memory_search. Same protection via FR-025 recall-time detection.',
  },

  // ── Identity tools (apps/api/src/identity/tools.ts) ────────────────────────
  {
    toolName: 'identity_get',
    category: 'mixed',
    justification:
      'Returns the channel identity prompt and team prompt stored in the channels table. These fields are editable by channel admins and by the agent itself (via identity_set); if the agent was previously compromised, identity_get becomes an exfiltration path for poisoned content. Conservative: treat as mixed so returned strings are filtered.',
  },
  {
    toolName: 'identity_set',
    category: 'system_generated',
    justification:
      'Write tool. Return value is { success: true } or { error: true, message }. The content being set is attacker-controllable but is detected on the turn input, not on the tool output.',
  },
  {
    toolName: 'team_context_set',
    category: 'system_generated',
    justification: 'Write tool. Same shape as identity_set.',
  },

  // ── CLI tools (apps/api/src/cli/registry.ts) ───────────────────────────────
  {
    toolName: 'aws_cli',
    category: 'mixed',
    justification:
      'Returns AWS API responses. Read-only subcommands (describe-*, list-*) return structured metadata, but fields like tag values, descriptions, and bucket names can contain user-editable strings from AWS users outside the PersonalClaw trust boundary. Treat as mixed.',
  },
  {
    toolName: 'github_cli',
    category: 'mixed',
    justification:
      'Returns GitHub API responses. Read-only subcommands still surface issue bodies, PR descriptions, comments, release notes — all user-editable text from any GitHub user. Treat as mixed; a compromised GitHub user could plant injection content.',
  },
  {
    toolName: 'curl_fetch',
    category: 'external_untrusted',
    justification: 'Fetches arbitrary URL content. Always attacker-reachable.',
  },

  // ── Browser tools (apps/api/src/browser/tools.ts) ──────────────────────────
  {
    toolName: 'browser_screenshot',
    category: 'system_generated',
    justification:
      'Return value is { image: base64, mimeType: "image/png" }. Binary image data cannot carry text-based injections directly; OCR-based detection is explicitly out of scope for v1 per spec §Edge Cases. The base64 string itself is not instruction text.',
  },
  {
    toolName: 'browser_scrape',
    category: 'external_untrusted',
    justification:
      'Returns text extracted from an arbitrary web page. Primary indirect-injection vector for external attackers.',
  },
  {
    toolName: 'browser_fill',
    category: 'system_generated',
    justification:
      'Form-fill tool. Return value is the submission status; the page content is not returned.',
  },

  // ── Schedule tools (apps/api/src/cron/tools.ts) ────────────────────────────
  {
    toolName: 'schedule_list',
    category: 'mixed',
    justification:
      'Returns stored schedules including the arbitrary `prompt` text field. Admins or the agent may have stored attacker-controlled content in the prompt — treat as mixed.',
  },
  {
    toolName: 'schedule_create',
    category: 'system_generated',
    justification: 'Write tool. Return value is { success, id } or { error }.',
  },
  {
    toolName: 'schedule_update',
    category: 'system_generated',
    justification: 'Write tool. Same shape as schedule_create.',
  },
  {
    toolName: 'schedule_delete',
    category: 'system_generated',
    justification: 'Write tool. Return value is { success } or { error }.',
  },

  // ── Sub-agent tools (apps/api/src/agent/sub-agent-tools.ts) ───────────────
  {
    toolName: 'spawn_subtask',
    category: 'system_generated',
    justification: 'Spawns a sub-task and returns a subtask id. Return value is opaque metadata.',
  },
  {
    toolName: 'get_subtask_result',
    category: 'already_detected',
    justification:
      'Returns the final output of a sub-agent run. Sub-agent runs go through the same detection pipeline as the parent agent, so the sub-task result has already been filtered by the time it is returned here.',
  },

  // ── Sandbox tools (apps/api/src/sandbox/tools.ts) ─────────────────────────
  {
    toolName: 'sandbox_exec',
    category: 'external_untrusted',
    justification:
      'Returns stdout and stderr of arbitrary shell commands. Output can contain any text the sandboxed process produces, including attacker-controlled content from network fetches or previously-written files.',
  },
  {
    toolName: 'sandbox_write_file',
    category: 'system_generated',
    justification:
      'Write tool. Return value is { success: true, path } or { error: true, message }.',
  },
  {
    toolName: 'sandbox_read_file',
    category: 'external_untrusted',
    justification:
      'Returns raw file contents from the sandbox workspace. Files may have been written by earlier sandbox_exec calls that fetched untrusted content.',
  },
  {
    toolName: 'sandbox_list_files',
    category: 'mixed',
    justification:
      'Returns file and directory names in the sandbox workspace. Filenames themselves can carry injection content if created by a malicious sandbox_exec. Treat as mixed.',
  },
  {
    toolName: 'sandbox_workspace_info',
    category: 'system_generated',
    justification:
      'Returns { workspacePath, exists, sizeBytes, createdAt }. All fields are system-generated metadata with no attacker path (workspacePath is fixed to /workspace).',
  },
] as const;

/**
 * Fast lookup map built from `TOOL_TRUST_REGISTRY`. Exported for the
 * self-test to enumerate; consumers should prefer `getToolTrustCategory()`.
 */
export const TOOL_TRUST_MAP: ReadonlyMap<string, ToolTrustEntry> = new Map(
  TOOL_TRUST_REGISTRY.map((entry) => [entry.toolName, entry]),
);

/**
 * Resolves a tool name to its trust category. Returns `external_untrusted`
 * for any tool not explicitly registered, per FR-030's fail-closed default.
 *
 * MCP tools are always routed through this function with the fallback behavior:
 * they are unknown to the static registry and therefore default to
 * `external_untrusted`, which can be overridden per-channel via the
 * `trust_mcp_tool` entries in `detection_overrides`.
 *
 * @param toolName The tool's registered name as seen by the agent
 * @returns The trust category to apply to the tool's output
 */
export function getToolTrustCategory(toolName: string): ToolTrustCategory {
  return TOOL_TRUST_MAP.get(toolName)?.category ?? 'external_untrusted';
}

/**
 * Enumerates the full set of statically-registered tool names that should
 * appear in `TOOL_TRUST_REGISTRY`. The self-test uses this to detect new
 * tools that were added without a trust decision.
 */
export function getRegisteredToolNames(): readonly string[] {
  return TOOL_TRUST_REGISTRY.map((entry) => entry.toolName);
}
